# -*- coding: utf-8 -*-
"""Scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKzWpFR3Ce7eDBlkBYiuZ2ARXGzCk019
"""

from PIL import Image
from IPython.display import display

from transformers import TrOCRProcessor, VisionEncoderDecoderModel

processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-handwritten')

model = VisionEncoderDecoderModel.from_pretrained('microsoft/trocr-base-handwritten')

def show_img(pathstr):
    img = Image.open(pathstr).convert('RGB')
    display(img)
    return img

ii = show_img('/content/thumb_1200_1698.png')

def ocr_img(src_img):
    pixel_values = processor(images=src_img, return_tensors="pt").pixel_values
    generated_ids = model.generate(pixel_values)
    return processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

ocr_img(ii)

line_height = 45
header_height = 150
margin = 150

for i in range(header_height, ii.size[1], line_height):
    ii2 = ii.crop((margin, i, ii.size[0], i + line_height))
    display(ii2)
    msg = ocr_img(ii2)
    print(msg)

print(msg)